### ISSUE TITLE
Mounting issues

### ISSUE THREAD

**Issue by faroutchris** [Scandit/scandit-react-native-datacapture-core#1]
Hello, 
I'm in the process of evaluating the new scandit react-native packages for a future upgrade. I'm running into some issues when mounting several instances of the scanner (on different screens).

In the first screen, everything seems to work fine. It's when trying to go to another screen and mount a new instance of the scanner that I bump into issues.

Before navigating I run these methods on the scanner:
```
this.captureMode.enabled = false;
if (this.camera) {
  this.captureMode.context.frameSource.switchToDesiredState(FrameSourceState.Off);
}
this.dataCaptureContext.dispose()
```
Am I missing something in my tear down?

This is the error message I receive on an Android device. Seems that it hasn't cleaned up everything (?)
![Screenshot_2020-10-23-12-54-24-258](https://user-images.githubusercontent.com/3967818/96999802-146c6f00-1536-11eb-9853-f3e48371bb08.jpg)

**Comment by ScanditSupport** [comment]
Hi @faroutchris 
Scandit support is happy to help you. Would you mind sharing a small project and reach out directly to the support team via:
https://support.scandit.com/hc/en-us
