### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by sumitagarwal31** [Scandit/scandit-react-native-datacapture-core#13]
I am using the 6.8.0 version and suddenly the library is creating an issue and I am unable to run the code. Strange as my app is live. 
Please help me out 
<img width="584" alt="Screenshot 2022-11-16 at 5 36 18 PM" src="https://user-images.githubusercontent.com/47786257/202176572-991c1a12-4189-4e09-9f14-15d970eada8d.png">

**Comment by ScanditSupport** [comment]
Hi,

Our scanning library requires the use of Java 8.

Please see the our documentation for system requirements: https://docs.scandit.com/data-capture-sdk/android/requirements.html.

In case you have more detailed questions, please feel free to reach out to us directly: https://support.scandit.com/hc/en-us/requests/new.

Best regards

Scandit Support Team
