### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by lucaong** [Scandit/scandit-react-native-datacapture-core#2]
It would be useful to make the TypeScript types available to the end user of the library (also for [scandit-react-native-datacapture-barcode](https://github.com/Scandit/scandit-react-native-datacapture-barcode) and other libraries). Currently, there are individual `.d.ts` type declaration files in the repo, but they are not bundled and not exposed to users of the library.

Usually one would bundle those type declarations with `tsc` into one single `.d.ts` file, and expose it from the `package.json` as the `"types": ...` field.

**Comment by ScanditSupport** [comment]
@lucaong thanks for your feedback. 
While the current Scandit SDK version 6.5 supports TypeScript, we confirm that the the type declarations are not bundled. However, we're already investigating which upcoming versions could provide this. 

If Scandit shall keep you posted on this, please reach out directly to us
https://support.scandit.com/hc/en-us/requests/new 

Best regards
Scandit Support Team

**Comment by ScanditSupport** [comment]
@lucaong the issue is resolved with Scandit SDK version 6.7.

Best regards
Scandit Support Team
