### ISSUE TITLE
Bug: style prop missing from DataCaptureView

### ISSUE THREAD

**Issue by TimP4w** [Scandit/scandit-react-native-datacapture-core#5]
I'm trying to style the `DataCaptureView` but typescript complains of the style prop missing even if it supports it (also as your example here: https://docs.scandit.com/data-capture-sdk/react-native/core/api/ui/data-capture-view.html).

And it is in fact missing here https://github.com/Scandit/scandit-react-native-datacapture-core/blob/master/js/DataCaptureView.d.ts#L11

Example:

```
<DataCaptureView
  style={styles.barcodePicker}
  context={scanditContext}
  ref={scannerRef}
/>
 ```
 
 Error:
 ```
 Type '{ style: { width: string; flex: number; marginBottom: number; }; context: DataCaptureContext; ref: MutableRefObject<any>; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<DataCaptureView> & Readonly<DataCaptureViewProps> & Readonly<...>'.
  Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DataCaptureView> & Readonly<DataCaptureViewProps> & Readonly<...>'.ts(2322)
 ```
   

- "scandit-react-native-datacapture-barcode": "^6.8.0-beta.2",
- "scandit-react-native-datacapture-core": "^6.8.0-beta.2",

**Comment by ScanditSupport** [comment]
@TimP4w thanks for adding your comment here. We'll look into how we can support style props. 

If you want us to inform you about the progress, please get in contact with us directly via 
https://support.scandit.com/hc/en-us/requests/new

**Comment by ScanditSupport** [comment]
Style Properties have been added to the DataCaptureView with 6.8.1.
