### ISSUE TITLE
The scandit SDKs don't work with React 17.0.1 when using npm

### ISSUE THREAD

**Issue by eebart** [Scandit/scandit-react-native-datacapture-core#7]
Using the scandit NPM packages: 

        "scandit-react-native-datacapture-barcode": "6.10.0",
        "scandit-react-native-datacapture-core": "6.10.0"

When running npm install on the unmodified test application BarcodeCaptureRejectSample, I get the following NPM error: 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: barcodecapturerejectsample@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from scandit-react-native-datacapture-barcode@6.10.0
npm ERR! node_modules/scandit-react-native-datacapture-barcode
npm ERR!   scandit-react-native-datacapture-barcode@"6.10.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

Installation does work with yarn. Entire package.json file: 

```
{
    "name": "barcodecapturerejectsample",
    "version": "1.0.0",
    "private": true,
    "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start"
    },
    "dependencies": {
        "react": "17.0.1",
        "react-native": "0.64.2",
        "scandit-react-native-datacapture-barcode": "6.10.0",
        "scandit-react-native-datacapture-core": "6.10.0"
    },
    "devDependencies": {
        "@babel/core": "^7.8.4",
        "@babel/runtime": "^7.8.4",
        "metro-react-native-babel-preset": "^0.59.0"
    },
    "jest": {
        "preset": "react-native"
    }
}
```

**Comment by ScanditSupport** [comment]
Hi @eebart 
thanks for adding your comment. 
We're actively looking into this but it seems to be only related to using npm as in our tests yarn was working correctly. Therefore, using yarn instead of npm is the workaround we're currently suggesting. 

We'll update the thread once we have more details. 

Please feel free to reach out to us directly in case of particular questions:
https://support.scandit.com/hc/en-us/requests/new 

Best regards
Scandit Support

**Comment by ScanditSupport** [comment]
Hi @eebart 
we haven't been able to reproduce the issue on our end (tested with npm 8.1.4 and 8.1.3, different node version from 12.x to 14.x). 
Can you make sure to clean the local cache and the package-lock.json and use the latest node and npm version? 

If you still experience issues, please reach out to us directly:
https://support.scandit.com/hc/en-us/requests/new 

Best regards
Your Scandit Support team
