### ISSUE TITLE
Update for react 17 dependency

### ISSUE THREAD

**Issue by 4iAmAve** [Scandit/scandit-react-native-datacapture-core#8]
Hi,

this is a simple one. For a version bump in our application, we would like to bump react to 17.0.1. However, we are also using this module. Since this is pinned to 16.x we are blocked in our efforts.

Therefore, please provide a new version with react 17.x as dependency. Or at least >= 16.8.0

Thank you in advance.

Regards

**Comment by ScanditSupport** [comment]
Duplicate of #7
