### ISSUE TITLE
No CHANGELOG or release notes

### ISSUE THREAD

**Issue by LaVielle** [Scandit/scandit-react-native-datacapture-core#9]
I noticed this repo does not contain a changelog, and not using "Releases" (only unannotated git tags).

I do see that you have pretty comprehensive Release Notes on your documentation site, which is very nice.
https://docs.scandit.com/data-capture-sdk/react-native/release-notes.html

However this is somewhat hard to find for us lazy devs used to looking for a CHANGELOG.md file or going to the "Releases" page of the repo.

It would be great if the repo "Releases" page would mirror what is in the docs, or at lease have a link pointing to them.

**Comment by ScanditSupport** [comment]
Hi @LaVielle 

I am afraid that our GitHub repositories are intended to host/show our samples.
For that reason, the changelog is not added to repo to avoid confusion. However, there is a README.md pointing towards the extensive official documentation.
 
In case you have any additional questions, please feel free to reach out to us directly:
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by LaVielle** [comment]
@ScanditSupport IMO the lack of release notes on the GH repo adds confusion rather than avoiding it. This is simply because GH is usually where developers find info about changes to a library, whether open source/free or not. Just a few examples:
- [RN release notes](https://github.com/facebook/react-native/releases)
- [RN Firebase changelog](https://github.com/invertase/react-native-firebase/blob/main/packages/app/CHANGELOG.md)
- [RN Branch release notes](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/releases)

So the reality is that devs expect to find release notes/changelogs in the repo, or at least very easy access to them from the repo. You can choose to organize your docs/release notes however you want, but since Scandit is not particularly cheap I think you can make it as easy as possible to find the info that we paying customers need to correctly use/update your SDK.

And btw, I'm not saying the solution needs to be complicated, with auto generated release notes during your build process, etc. A simple CHANGELOG.md file pointing to your release notes page would do. Which is exactly what I propose in PR https://github.com/Scandit/scandit-react-native-datacapture-core/pull/10

✌️

**Comment by ScanditSupport** [comment]
@LaVielle  

I've notified our product team with your request and we'll look into whether we change the approach in upcoming releases. 

For the upcoming 6.12, it will still remain as it is. 
I'm  closing the pull request as the repo is served based on our release cycles and we have noted your request.

In case you have any additional questions, please feel free to reach out to us directly:
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
